### ISSUE TITLE
[BUG]  Cannot create container for service connector

### ISSUE THREAD

**Issue by BerengarWLehr** [nmshd/feedback#7]
I can not start the docker image of the connector

**To Reproduce**
(mongo db is already running, config file is mounted as described on https://enmeshed.eu/integrate/connector-installation)
```
docker-compose up connector
```

**Expected behavior**
A container starting, possibly showing errors in the config file or just success

**Screenshots**
```
mongodb is up-to-date
Creating connector ... error

ERROR: for connector  Cannot create container for service connector: No command specified

ERROR: for connector  Cannot create container for service connector: No command specified
ERROR: Encountered errors while bringing up the project.
```

**Environment**
docker vm

**Comment by jkoenig134** [comment]
Please provide your compose file.

**Comment by BerengarWLehr** [comment]
```
version: "3.7"

services:
  connector:
    container_name: connector
    image: ghcr.io/nmshd/connector:2.1.2
    environment:
      CUSTOM_CONFIG_LOCATION: "/config.json"
    ports:
      - 8081:80
    volumes:
      - ./config.json:/config.json:RO
      - ./logs:/usr/app/logs
    depends_on:
      - mongodb
    restart: always

  mongodb:
    container_name: mongodb
    image: mongo:4.4.6
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongo
      MONGO_INITDB_ROOT_PASSWORD: #########
    volumes:
      - mongodb_data:/data/db
    restart: always

volumes:
  mongodb_data:
```
